language: rust

rust:
  - stable

stages:
  - usually
  - name: publish
    if: tag IS present

jobs:
  include:
    - stage: usually
      name: Package rsnowboy
      script:
        - sudo apt-get install -y libgsl-dev
        - cargo run --example simple
    - stage: publish
      name: Publish rtdlib to crates.io
      script:
        - sudo apt-get install -y libgsl-dev
        - cargo login $CRATES_TOKEN
        - cargo publish
